project_id = "qlffjhyciwabyzolzdjb"

[functions.delete-account]
verify_jwt = false

[functions.update-email]
verify_jwt = false

[functions.check-customer-auth]
verify_jwt = false

[functions.cleanup-orphaned-auth]
verify_jwt = false

[functions.reassign-customer-profile]
verify_jwt = false

[functions.tap-create-charge]
verify_jwt = false

[functions.tap-webhook]
verify_jwt = false

[functions.tap-check-status]
verify_jwt = false

[functions.tap-retry-payment]
verify_jwt = false
