-- Insert all countries with phone codes, ISO codes, and currency information
-- Using ON CONFLICT to update existing entries

INSERT INTO countries (id, name, phone_code, currency_code, currency_symbol, is_active) VALUES
-- A
('af', 'Afghanistan', '+93', 'AFN', '؋', true),
('al', 'Albania', '+355', 'ALL', 'L', true),
('dz', 'Algeria', '+213', 'DZD', 'د.ج', true),
('as', 'American Samoa', '+1', 'USD', '$', true),
('ad', 'Andorra', '+376', 'EUR', '€', true),
('ao', 'Angola', '+244', 'AOA', 'Kz', true),
('ai', 'Anguilla', '+1', 'XCD', '$', true),
('ag', 'Antigua and Barbuda', '+1', 'XCD', '$', true),
('ar', 'Argentina', '+54', 'ARS', '$', true),
('am', 'Armenia', '+374', 'AMD', '֏', true),
('aw', 'Aruba', '+297', 'AWG', 'ƒ', true),
('ac', 'Ascension', '+247', 'SHP', '£', true),
('au', 'Australia', '+61', 'AUD', '$', true),
('at', 'Austria', '+43', 'EUR', '€', true),
('az', 'Azerbaijan', '+994', 'AZN', '₼', true),
-- B
('bs', 'Bahamas', '+1', 'BSD', '$', true),
('bh', 'Bahrain', '+973', 'BHD', 'د.ب', true),
('bd', 'Bangladesh', '+880', 'BDT', '৳', true),
('bb', 'Barbados', '+1', 'BBD', '$', true),
('by', 'Belarus', '+375', 'BYN', 'Br', true),
('be', 'Belgium', '+32', 'EUR', '€', true),
('bz', 'Belize', '+501', 'BZD', '$', true),
('bj', 'Benin', '+229', 'XOF', 'Fr', true),
('bm', 'Bermuda', '+1', 'BMD', '$', true),
('bt', 'Bhutan', '+975', 'BTN', 'Nu.', true),
('bo', 'Bolivia', '+591', 'BOB', 'Bs.', true),
('ba', 'Bosnia and Herzegovina', '+387', 'BAM', 'KM', true),
('bw', 'Botswana', '+267', 'BWP', 'P', true),
('br', 'Brazil', '+55', 'BRL', 'R$', true),
('vg', 'British Virgin Islands', '+1', 'USD', '$', true),
('bn', 'Brunei Darussalam', '+673', 'BND', '$', true),
('bg', 'Bulgaria', '+359', 'BGN', 'лв', true),
('bf', 'Burkina Faso', '+226', 'XOF', 'Fr', true),
('bi', 'Burundi', '+257', 'BIF', 'Fr', true),
-- C
('kh', 'Cambodia', '+855', 'KHR', '៛', true),
('cm', 'Cameroon', '+237', 'XAF', 'Fr', true),
('ca', 'Canada', '+1', 'CAD', '$', true),
('cv', 'Cape Verde', '+238', 'CVE', '$', true),
('ky', 'Cayman Islands', '+1', 'KYD', '$', true),
('cf', 'Central African Republic', '+236', 'XAF', 'Fr', true),
('td', 'Chad', '+235', 'XAF', 'Fr', true),
('cl', 'Chile', '+56', 'CLP', '$', true),
('cn', 'China', '+86', 'CNY', '¥', true),
('co', 'Colombia', '+57', 'COP', '$', true),
('km', 'Comoros', '+269', 'KMF', 'Fr', true),
('cg', 'Congo', '+242', 'XAF', 'Fr', true),
('cd', 'Democratic Republic of the Congo', '+243', 'CDF', 'Fr', true),
('ck', 'Cook Islands', '+682', 'NZD', '$', true),
('cr', 'Costa Rica', '+506', 'CRC', '₡', true),
('ci', 'Côte d''Ivoire', '+225', 'XOF', 'Fr', true),
('hr', 'Croatia', '+385', 'EUR', '€', true),
('cu', 'Cuba', '+53', 'CUP', '$', true),
('cw', 'Curaçao', '+599', 'ANG', 'ƒ', true),
('cy', 'Cyprus', '+357', 'EUR', '€', true),
('cz', 'Czech Republic', '+420', 'CZK', 'Kč', true),
-- D
('dk', 'Denmark', '+45', 'DKK', 'kr', true),
('dg', 'Diego Garcia', '+246', 'USD', '$', true),
('dj', 'Djibouti', '+253', 'DJF', 'Fr', true),
('dm', 'Dominica', '+1', 'XCD', '$', true),
('do', 'Dominican Republic', '+1', 'DOP', '$', true),
-- E
('ec', 'Ecuador', '+593', 'USD', '$', true),
('eg', 'Egypt', '+20', 'EGP', '£', true),
('sv', 'El Salvador', '+503', 'USD', '$', true),
('gq', 'Equatorial Guinea', '+240', 'XAF', 'Fr', true),
('er', 'Eritrea', '+291', 'ERN', 'Nfk', true),
('ee', 'Estonia', '+372', 'EUR', '€', true),
('sz', 'Eswatini (Swaziland)', '+268', 'SZL', 'L', true),
('et', 'Ethiopia', '+251', 'ETB', 'Br', true),
-- F
('fk', 'Falkland Islands', '+500', 'FKP', '£', true),
('fo', 'Faroe Islands', '+298', 'DKK', 'kr', true),
('fj', 'Fiji', '+679', 'FJD', '$', true),
('fi', 'Finland', '+358', 'EUR', '€', true),
('fr', 'France', '+33', 'EUR', '€', true),
('gf', 'French Guiana', '+594', 'EUR', '€', true),
('pf', 'French Polynesia', '+689', 'XPF', 'Fr', true),
-- G
('ga', 'Gabon', '+241', 'XAF', 'Fr', true),
('gm', 'Gambia', '+220', 'GMD', 'D', true),
('ge', 'Georgia', '+995', 'GEL', '₾', true),
('de', 'Germany', '+49', 'EUR', '€', true),
('gh', 'Ghana', '+233', 'GHS', '₵', true),
('gi', 'Gibraltar', '+350', 'GIP', '£', true),
('gr', 'Greece', '+30', 'EUR', '€', true),
('gl', 'Greenland', '+299', 'DKK', 'kr', true),
('gd', 'Grenada', '+1', 'XCD', '$', true),
('gp', 'Guadeloupe', '+590', 'EUR', '€', true),
('gu', 'Guam', '+1', 'USD', '$', true),
('gt', 'Guatemala', '+502', 'GTQ', 'Q', true),
('gg', 'Guernsey', '+44', 'GBP', '£', true),
('gn', 'Guinea', '+224', 'GNF', 'Fr', true),
('gw', 'Guinea-Bissau', '+245', 'XOF', 'Fr', true),
('gy', 'Guyana', '+592', 'GYD', '$', true),
-- H
('ht', 'Haiti', '+509', 'HTG', 'G', true),
('va', 'Holy See (Vatican City State)', '+379', 'EUR', '€', true),
('hn', 'Honduras', '+504', 'HNL', 'L', true),
('hk', 'Hong Kong', '+852', 'HKD', '$', true),
('hu', 'Hungary', '+36', 'HUF', 'Ft', true),
-- I
('is', 'Iceland', '+354', 'ISK', 'kr', true),
('in', 'India', '+91', 'INR', '₹', true),
('id', 'Indonesia', '+62', 'IDR', 'Rp', true),
('ir', 'Iran', '+98', 'IRR', '﷼', true),
('iq', 'Iraq', '+964', 'IQD', 'ع.د', true),
('ie', 'Ireland', '+353', 'EUR', '€', true),
('im', 'Isle of Man', '+44', 'GBP', '£', true),
('il', 'Israel', '+972', 'ILS', '₪', true),
('it', 'Italy', '+39', 'EUR', '€', true),
-- J
('jm', 'Jamaica', '+1', 'JMD', '$', true),
('jp', 'Japan', '+81', 'JPY', '¥', true),
('je', 'Jersey', '+44', 'GBP', '£', true),
('jo', 'Jordan', '+962', 'JOD', 'د.ا', true),
-- K
('kz', 'Kazakhstan', '+7', 'KZT', '₸', true),
('ke', 'Kenya', '+254', 'KES', 'Sh', true),
('ki', 'Kiribati', '+686', 'AUD', '$', true),
('kp', 'Democratic People''s Republic of Korea', '+850', 'KPW', '₩', true),
('kr', 'South Korea', '+82', 'KRW', '₩', true),
('xk', 'Kosovo', '+383', 'EUR', '€', true),
('kw', 'Kuwait', '+965', 'KWD', 'د.ك', true),
('kg', 'Kyrgyzstan', '+996', 'KGS', 'с', true),
-- L
('la', 'Lao People''s Democratic Republic', '+856', 'LAK', '₭', true),
('lv', 'Latvia', '+371', 'EUR', '€', true),
('lb', 'Lebanon', '+961', 'LBP', '£', true),
('ls', 'Lesotho', '+266', 'LSL', 'L', true),
('lr', 'Liberia', '+231', 'LRD', '$', true),
('ly', 'Libya', '+218', 'LYD', 'ل.د', true),
('li', 'Liechtenstein', '+423', 'CHF', 'Fr', true),
('lt', 'Lithuania', '+370', 'EUR', '€', true),
('lu', 'Luxembourg', '+352', 'EUR', '€', true),
-- M
('mo', 'Macao', '+853', 'MOP', 'P', true),
('mg', 'Madagascar', '+261', 'MGA', 'Ar', true),
('mw', 'Malawi', '+265', 'MWK', 'MK', true),
('my', 'Malaysia', '+60', 'MYR', 'RM', true),
('mv', 'Maldives', '+960', 'MVR', 'ރ.', true),
('ml', 'Mali', '+223', 'XOF', 'Fr', true),
('mt', 'Malta', '+356', 'EUR', '€', true),
('mh', 'Marshall Islands', '+692', 'USD', '$', true),
('mq', 'Martinique', '+596', 'EUR', '€', true),
('mr', 'Mauritania', '+222', 'MRU', 'UM', true),
('mu', 'Mauritius', '+230', 'MUR', '₨', true),
('yt', 'Mayotte', '+269', 'EUR', '€', true),
('mx', 'Mexico', '+52', 'MXN', '$', true),
('fm', 'Micronesia (Federated States of)', '+691', 'USD', '$', true),
('md', 'Moldova', '+373', 'MDL', 'L', true),
('mc', 'Monaco', '+377', 'EUR', '€', true),
('mn', 'Mongolia', '+976', 'MNT', '₮', true),
('me', 'Montenegro', '+382', 'EUR', '€', true),
('ms', 'Montserrat', '+1', 'XCD', '$', true),
('ma', 'Morocco', '+212', 'MAD', 'د.م.', true),
('mz', 'Mozambique', '+258', 'MZN', 'MT', true),
('mm', 'Myanmar', '+95', 'MMK', 'Ks', true),
-- N
('na', 'Namibia', '+264', 'NAD', '$', true),
('nr', 'Nauru', '+674', 'AUD', '$', true),
('np', 'Nepal', '+977', 'NPR', '₨', true),
('nl', 'Netherlands', '+31', 'EUR', '€', true),
('nc', 'New Caledonia', '+687', 'XPF', 'Fr', true),
('nz', 'New Zealand', '+64', 'NZD', '$', true),
('ni', 'Nicaragua', '+505', 'NIO', 'C$', true),
('ne', 'Niger', '+227', 'XOF', 'Fr', true),
('ng', 'Nigeria', '+234', 'NGN', '₦', true),
('nu', 'Niue', '+683', 'NZD', '$', true),
('nf', 'Norfolk Island', '+672', 'AUD', '$', true),
('mk', 'North Macedonia', '+389', 'MKD', 'ден', true),
('mp', 'Northern Mariana Islands', '+1', 'USD', '$', true),
('no', 'Norway', '+47', 'NOK', 'kr', true),
-- O
('om', 'Oman', '+968', 'OMR', 'ر.ع.', true),
-- P
('pk', 'Pakistan', '+92', 'PKR', '₨', true),
('pw', 'Palau', '+680', 'USD', '$', true),
('ps', 'Palestine', '+970', 'ILS', '₪', true),
('pa', 'Panama', '+507', 'PAB', 'B/.', true),
('pg', 'Papua New Guinea', '+675', 'PGK', 'K', true),
('py', 'Paraguay', '+595', 'PYG', '₲', true),
('pe', 'Peru', '+51', 'PEN', 'S/', true),
('ph', 'Philippines', '+63', 'PHP', '₱', true),
('pn', 'Pitcairn Islands', '+64', 'NZD', '$', true),
('pl', 'Poland', '+48', 'PLN', 'zł', true),
('pt', 'Portugal', '+351', 'EUR', '€', true),
('pr', 'Puerto Rico', '+1', 'USD', '$', true),
-- Q
('qa', 'Qatar', '+974', 'QAR', 'ر.ق', true),
-- R
('re', 'Réunion', '+262', 'EUR', '€', true),
('ro', 'Romania', '+40', 'RON', 'lei', true),
('ru', 'Russian Federation', '+7', 'RUB', '₽', true),
('rw', 'Rwanda', '+250', 'RWF', 'Fr', true),
-- S
('bl', 'Saint Barthélemy', '+590', 'EUR', '€', true),
('sh', 'Saint Helena', '+249', 'SHP', '£', true),
('kn', 'Saint Kitts and Nevis', '+1', 'XCD', '$', true),
('lc', 'Saint Lucia', '+1', 'XCD', '$', true),
('mf', 'Saint Martin (French part)', '+590', 'EUR', '€', true),
('pm', 'Saint Pierre and Miquelon', '+508', 'EUR', '€', true),
('vc', 'Saint Vincent and the Grenadines', '+1', 'XCD', '$', true),
('ws', 'Samoa', '+685', 'WST', 'T', true),
('sm', 'San Marino', '+378', 'EUR', '€', true),
('st', 'Sao Tome and Principe', '+239', 'STN', 'Db', true),
('sa', 'Saudi Arabia', '+966', 'SAR', 'ر.س', true),
('sn', 'Senegal', '+221', 'XOF', 'Fr', true),
('rs', 'Serbia', '+381', 'RSD', 'дин', true),
('sc', 'Seychelles', '+248', 'SCR', '₨', true),
('sl', 'Sierra Leone', '+232', 'SLL', 'Le', true),
('sg', 'Singapore', '+65', 'SGD', '$', true),
('sx', 'Sint Maarten (Dutch part)', '+1', 'ANG', 'ƒ', true),
('sk', 'Slovakia', '+421', 'EUR', '€', true),
('si', 'Slovenia', '+386', 'EUR', '€', true),
('sb', 'Solomon Islands', '+677', 'SBD', '$', true),
('so', 'Somalia', '+252', 'SOS', 'Sh', true),
('za', 'South Africa', '+27', 'ZAR', 'R', true),
('gs', 'South Georgia and the South Sandwich Islands', '+500', 'GBP', '£', true),
('ss', 'South Sudan', '+211', 'SSP', '£', true),
('es', 'Spain', '+34', 'EUR', '€', true),
('lk', 'Sri Lanka', '+94', 'LKR', 'Rs', true),
('sd', 'Sudan', '+249', 'SDG', 'ج.س.', true),
('sr', 'Suriname', '+597', 'SRD', '$', true),
('se', 'Sweden', '+46', 'SEK', 'kr', true),
('ch', 'Switzerland', '+41', 'CHF', 'Fr', true),
('sy', 'Syrian Arab Republic', '+963', 'SYP', '£', true),
-- T
('tw', 'Taiwan (Province of China)', '+886', 'TWD', '$', true),
('tj', 'Tajikistan', '+992', 'TJS', 'ЅМ', true),
('tz', 'Tanzania', '+255', 'TZS', 'Sh', true),
('th', 'Thailand', '+66', 'THB', '฿', true),
('tl', 'Timor-Leste', '+670', 'USD', '$', true),
('tg', 'Togo', '+228', 'XOF', 'Fr', true),
('to', 'Tonga', '+676', 'TOP', 'T$', true),
('tt', 'Trinidad and Tobago', '+1', 'TTD', '$', true),
('tn', 'Tunisia', '+216', 'TND', 'د.ت', true),
('tr', 'Turkey', '+90', 'TRY', '₺', true),
('tm', 'Turkmenistan', '+993', 'TMT', 'm', true),
('tv', 'Tuvalu', '+688', 'AUD', '$', true),
-- U
('ug', 'Uganda', '+256', 'UGX', 'Sh', true),
('ua', 'Ukraine', '+380', 'UAH', '₴', true),
('ae', 'United Arab Emirates', '+971', 'AED', 'د.إ', true),
('gb', 'United Kingdom', '+44', 'GBP', '£', true),
('us', 'United States of America', '+1', 'USD', '$', true),
('uy', 'Uruguay', '+598', 'UYU', '$', true),
('uz', 'Uzbekistan', '+998', 'UZS', 'so''m', true),
-- V
('vu', 'Vanuatu', '+678', 'VUV', 'Vt', true),
('ve', 'Venezuela (Bolivarian Republic of)', '+58', 'VES', 'Bs.', true),
('vn', 'Vietnam', '+84', 'VND', '₫', true),
-- Y
('ye', 'Yemen (Republic of)', '+967', 'YER', '﷼', true),
-- Z
('zm', 'Zambia', '+260', 'ZMW', 'ZK', true),
('zw', 'Zimbabwe', '+263', 'ZWL', '$', true)
ON CONFLICT (id) 
DO UPDATE SET
  name = EXCLUDED.name,
  phone_code = EXCLUDED.phone_code,
  currency_code = EXCLUDED.currency_code,
  currency_symbol = EXCLUDED.currency_symbol,
  is_active = EXCLUDED.is_active;