-- Populate countries table with comprehensive country codes
INSERT INTO countries (id, name, phone_code, currency_code, currency_symbol, is_active) VALUES
('us', 'United States', '+1', 'USD', '$', true),
('uk', 'United Kingdom', '+44', 'GBP', '£', true),
('ae', 'United Arab Emirates', '+971', 'AED', 'د.إ', true),
('sa', 'Saudi Arabia', '+966', 'SAR', 'ر.س', true),
('bh', 'Bahrain', '+973', 'BHD', 'د.ب', true),
('om', 'Oman', '+968', 'OMR', 'ر.ع.', true),
('in', 'India', '+91', 'INR', '₹', true),
('pk', 'Pakistan', '+92', 'PKR', '₨', true),
('bd', 'Bangladesh', '+880', 'BDT', '৳', true),
('eg', 'Egypt', '+20', 'EGP', 'ج.م', true),
('jo', 'Jordan', '+962', 'JOD', 'د.ا', true),
('lb', 'Lebanon', '+961', 'LBP', 'ل.ل', true),
('ca', 'Canada', '+1', 'CAD', 'C$', true),
('au', 'Australia', '+61', 'AUD', 'A$', true),
('de', 'Germany', '+49', 'EUR', '€', true),
('fr', 'France', '+33', 'EUR', '€', true),
('it', 'Italy', '+39', 'EUR', '€', true),
('es', 'Spain', '+34', 'EUR', '€', true),
('nl', 'Netherlands', '+31', 'EUR', '€', true),
('ph', 'Philippines', '+63', 'PHP', '₱', true),
('my', 'Malaysia', '+60', 'MYR', 'RM', true),
('sg', 'Singapore', '+65', 'SGD', 'S$', true),
('th', 'Thailand', '+66', 'THB', '฿', true),
('jp', 'Japan', '+81', 'JPY', '¥', true),
('kr', 'South Korea', '+82', 'KRW', '₩', true),
('cn', 'China', '+86', 'CNY', '¥', true),
('tr', 'Turkey', '+90', 'TRY', '₺', true),
('za', 'South Africa', '+27', 'ZAR', 'R', true),
('br', 'Brazil', '+55', 'BRL', 'R$', true),
('mx', 'Mexico', '+52', 'MXN', '$', true)
ON CONFLICT (id) DO NOTHING;