UPDATE categories SET name_ar = CASE name
  WHEN 'Islamic Cakes' THEN 'كيكات إسلامية'
  WHEN 'Retro Cakes' THEN 'كيكات ريترو'
  WHEN 'Girls Cakes' THEN 'كيكات بنات'
  WHEN 'For Girls' THEN 'كيكات بنات'
  WHEN 'Boys Cakes' THEN 'كيكات أولاد'
  WHEN 'Anime Cakes' THEN 'كيكات أنمي'
  WHEN 'European Cakes' THEN 'كيكات أوروبية'
  WHEN 'Classic Cakes' THEN 'كيكات كلاسيكية'
  WHEN 'Comic Cakes' THEN 'كيكات كوميك'
  WHEN 'Cupcakes' THEN 'كب كيك'
  WHEN 'Customized Cakes' THEN 'كيكات مخصصة'
  WHEN 'Family Cakes' THEN 'كيكات عائلية'
  WHEN 'Flower & Balloon Cakes' THEN 'كيكات ورد وبالون'
  WHEN 'Gender Reveal Cakes' THEN 'كيكات كشف الجنس'
  WHEN 'Graduation Corner' THEN 'ركن التخرج'
  WHEN 'Marble Cakes' THEN 'كيكات ماربل'
  WHEN 'Movies & TV Cakes' THEN 'كيكات أفلام وتلفزيون'
  WHEN 'Movies & TV' THEN 'أفلام وتلفزيون'
  WHEN 'Photo Cakes' THEN 'كيكات صور'
  WHEN 'Small Cakes' THEN 'كيكات صغيرة'
  WHEN 'Special Cakes' THEN 'كيكات خاصة'
  WHEN 'Special Items' THEN 'منتجات خاصة'
  WHEN 'Sports Corner' THEN 'ركن الرياضة'
  WHEN 'Zodiac Sign Cakes' THEN 'كيكات الأبراج'
  WHEN 'Valentine Corner' THEN 'ركن الفالنتاين'
  WHEN 'Wedding Corner' THEN 'ركن الزفاف'
  WHEN 'Candles & Toppers' THEN 'شموع وتوبرز'
  WHEN 'Chocolates & Brownies' THEN 'شوكولاتة وبراونيز'
  WHEN 'Mothers Day Cakes' THEN 'كيكات عيد الأم'
  WHEN 'Mother''s Day Cakes' THEN 'كيكات عيد الأم'
  ELSE name_ar
END;