// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlffjhyciwabyzolzdjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsZmZqaHljaXdhYnl6b2x6ZGpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODA1MjYsImV4cCI6MjA3MDA1NjUyNn0.ZvVzOhXzYYNa_BgYCIKnWw6bz0n2-R8LUdMjLv2A110";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});